=== GLTron3000/DPR_XML/master.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT master (infos, intervenants, parcours, semestres, unites, groupes)><!---->

<!ELEMENT infos (nom, resume, ref-parcour*, ref-intervenant*)> <!---->
<!ATTLIST infos id ID #IMPLIED> <!---->

<!ELEMENT parcours (parcour+)> <!---->

<!ELEMENT parcour (nom, nom-court, resume, ref-intervenant+)> <!-- ref-intervenant pour le responsable du parcour -->
<!ATTLIST parcour id ID #IMPLIED> <!---->

<!ELEMENT ref-parcour     (#PCDATA)> <!---->
<!ATTLIST ref-parcour ref IDREF #REQUIRED> <!---->

<!ELEMENT semestres (semestre+)> <!---->

<!ELEMENT semestre (nom, ref-unite+, ref-groupe*, ref-parcour+)> <!---->
<!ATTLIST semestre id ID #IMPLIED> <!---->

<!ELEMENT ref-semestre (#PCDATA)> <!---->
<!ATTLIST ref-semestre ref IDREF #REQUIRED> <!---->

<!ELEMENT intervenants (intervenant+)> <!---->

<!ELEMENT intervenant (nom, prenom, email)> <!---->
<!ATTLIST intervenant id ID #IMPLIED> <!---->

<!ELEMENT ref-intervenant (#PCDATA)> <!---->
<!ATTLIST ref-intervenant ref IDREF #REQUIRED> <!---->

<!ELEMENT unites (unite+)> <!---->

<!ELEMENT unite (nom, credits, resume, ref-intervenant*, ref-parcour+)> <!---->
<!ATTLIST unite id ID #IMPLIED> <!---->
<!ATTLIST unite role (obligatoire|option) #IMPLIED> <!---->

<!ELEMENT ref-unite       (#PCDATA)> <!---->
<!ATTLIST ref-unite ref IDREF #REQUIRED> <!---->

<!ELEMENT groupe (nom, credits, ref-unite*, ref-groupe*, ref-parcour+)> 
<!ATTLIST groupe id ID #IMPLIED> 

<!ELEMENT groupes (groupe+)> <!---->

<!ELEMENT ref-groupe (#PCDATA)> <!---->
<!ATTLIST ref-groupe ref IDREF #REQUIRED> <!---->


<!ELEMENT credits         (#PCDATA)> 
<!ELEMENT resume          (p|ul|ol)*>

<!ELEMENT nom             (#PCDATA)> 
<!ELEMENT nom-court       (#PCDATA)> 

<!ELEMENT prenom          (#PCDATA)> 
<!ELEMENT email           (#PCDATA)> 

<!ELEMENT ol			  (li*) >
<!ELEMENT ul			  (li*) >
<!ELEMENT li			  (#PCDATA|b|i|u|ul)* >
<!ELEMENT p				  (#PCDATA|b|i|u|br)* >
<!ELEMENT b				  (#PCDATA) >
<!ELEMENT i				  (#PCDATA) >
<!ELEMENT u				  (#PCDATA) >

=== GLTron3000/DPR_XML/master.xml
<?xml version="1.0"?>
<!DOCTYPE master SYSTEM "master.dtd">
<master>
  <infos id="ME5SIN">
    <nom>Informatique</nom>
    <resume>
      <p>
        <t>Le master Informatique a pour vocation la formation de professionnels de l'informatique au niveau bac+5. L'objectif est d'offrir aux étudiants un large spectre de compétences et de savoirs afin de rendre accessibles des emplois de haut niveau dans le monde de l'entreprise, ainsi que dans celui de la recherche, ou dans d'autres organisations. La mention informatique offre une palette de six parcours adaptés à plusieurs secteurs de l'informatique. Les diplômés auront donc accès à une grande diversité de métiers et de carrières.</t>
      </p>
    </resume>
    <ref-parcour ref="ME5SIN-PRSIN5AA"/>
    <ref-parcour ref="ME5SIN-PRSIN5AB"/>
    <ref-parcour ref="ME5SIN-PRSIN5AC"/>
    <ref-parcour ref="ME5SIN-PRSIN5AD"/>
    <ref-parcour ref="ME5SIN-PRSIN5AE"/>
    <ref-parcour ref="ME5SIN-PRSIN5AF"/>
    <ref-intervenant ref="IN18"/>
  </infos>
  <intervenants>
    <intervenant id="II1000">
      <nom>ARTIÈRES</nom>
      <prenom>Thierry</prenom>
      <email>thierry.artieres@lif.univ-mrs.fr</email>
    </intervenant>
    <intervenant id="IN1021">
      <nom>BERTOLISSI</nom>
      <prenom>Clara</prenom>
      <email>clara.bertolissi@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN10388">
      <nom>FAVRE</nom>
      <prenom>Benoit</prenom>
      <email>benoit.favre@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN12068">
      <nom>HABET</nom>
      <prenom>Djamal</prenom>
      <email>djamal.habet@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN12141">
      <nom>JEGOU</nom>
      <prenom>Philippe</prenom>
      <email>philippe.jegou@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN12292">
      <nom>TERRIOUX</nom>
      <prenom>Cyril</prenom>
      <email>cyril.terrioux@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN12507">
      <nom>HAMRI</nom>
      <prenom>Maamar El amine</prenom>
      <email>amine.hamri@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN12544">
      <nom>BOUCELMA</nom>
      <prenom>Omar</prenom>
      <email>omar.boucelma@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN1262">
      <nom>CAPPONI</nom>
      <prenom>Cecile</prenom>
      <email>cecile.capponi@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN12883">
      <nom>FOURNIER</nom>
      <prenom>Sebastien</prenom>
      <email>sebastien.fournier@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN12969">
      <nom>RENE CHABAROT</nom>
      <prenom>Lydie</prenom>
      <email>lydie.rene@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN14003">
      <nom>DUPE</nom>
      <prenom>Francois Xavier</prenom>
      <email>francois-xavier.dupe@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN14758">
      <nom>BROCHE</nom>
      <prenom>Martine</prenom>
      <email>martine.broche@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN16208">
      <nom>COUETOUX</nom>
      <prenom>Basile</prenom>
      <email>basile.couetoux@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN16625">
      <nom>SELLAMI</nom>
      <prenom>Sana</prenom>
      <email>sana.sellami@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN18">
      <nom>MASSAT</nom>
      <prenom>Jean-Luc</prenom>
      <email>jean-luc.massat@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN19444">
      <nom>KADRI</nom>
      <prenom>Hachem</prenom>
      <email>hachem.kadri@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN21048">
      <nom>RAMISCH</nom>
      <prenom>Carlos</prenom>
      <email>carlos.ramisch@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN2301">
      <nom>HUBERT</nom>
      <prenom>Florence</prenom>
      <email>florence.hubert@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN23202">
      <nom>ARRIGHI</nom>
      <prenom>Pablo</prenom>
      <email>pablo.arrighi@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN23203">
      <nom>PERROT</nom>
      <prenom>Kevin</prenom>
      <email>kevin.perrot@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN25554">
      <nom>MONMEGE</nom>
      <prenom>Benjamin</prenom>
      <email>benjamin.monmege@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN25567">
      <nom>CONTENSIN</nom>
      <prenom>Magali</prenom>
      <email>magali.contensin@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN2563">
      <nom>GODARD</nom>
      <prenom>Emmanuel</prenom>
      <email>emmanuel.godard@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN3524">
      <nom>LUGIEZ</nom>
      <prenom>Denis</prenom>
      <email>denis.lugiez@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN36256">
      <nom>VILLEVALOIS</nom>
      <prenom>Didier</prenom>
      <email>didier.villevalois@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN37076">
      <nom>HOAREAU</nom>
      <prenom>Nicolas</prenom>
      <email>nicolas.hoareau@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN37097">
      <nom>ROMANO</nom>
      <prenom>Christian</prenom>
      <email>christian.romano@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN37426">
      <nom>JULLIEN</nom>
      <prenom>Christophe</prenom>
      <email>christophe.jullien@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN37528">
      <nom>DI MOLFETTA</nom>
      <prenom>Giuseppe</prenom>
      <email>giuseppe.di-molfetta@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN38232">
      <nom>IMBS</nom>
      <prenom>Damien</prenom>
      <email>damien.imbs@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN4595">
      <nom>REYNIER</nom>
      <prenom>Pierre-Alain</prenom>
      <email>pierre-alain.reynier@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN4718">
      <nom>EYRAUD</nom>
      <prenom>Remi</prenom>
      <email>remi.eyraud@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN4872">
      <nom>RAFFIN</nom>
      <prenom>Romain</prenom>
      <email>romain.raffin@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN4955">
      <nom>SANTOCANALE</nom>
      <prenom>Luigi</prenom>
      <email>luigi.santocanale@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN616">
      <nom>AGOPIAN</nom>
      <prenom>Roland</prenom>
      <email>roland.agopian@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN7566">
      <nom>CEPOI</nom>
      <prenom>Victor</prenom>
      <email>victor.cepoi@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN7574">
      <nom>SEQUEIRA</nom>
      <prenom>Jean</prenom>
      <email>jean.sequeira@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN7722">
      <nom>NOVELLI</nom>
      <prenom>Noel</prenom>
      <email>noel.novelli@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN7779">
      <nom>THIEL</nom>
      <prenom>Edouard</prenom>
      <email>edouard.thiel@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN7931">
      <nom>RISCH</nom>
      <prenom>Sylvie</prenom>
      <email>sylvie.risch@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN8086">
      <nom>VAXES</nom>
      <prenom>Yann</prenom>
      <email>yann.vaxes@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN8416">
      <nom>MARI</nom>
      <prenom>Jean Luc</prenom>
      <email>jean-luc.mari@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN8703">
      <nom>TICHIT</nom>
      <prenom>Laurent</prenom>
      <email>laurent.tichit@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN9224">
      <nom>MORIN</nom>
      <prenom>Remi</prenom>
      <email>remi.morin@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN9941">
      <nom>BECHET</nom>
      <prenom>Frederic</prenom>
      <email>frederic.bechet@univ-amu.fr</email>
    </intervenant>
    <intervenant id="IN9944">
      <nom>LEFEVRE</nom>
      <prenom>Julien</prenom>
      <email>julien.lefevre@univ-amu.fr</email>
    </intervenant>
  </intervenants>
  <parcours>
    <parcour id="ME5SIN-PRSIN5AA">
      <nom>Parcours type : Fiabilité et sécurité informatique (FSI)</nom>
      <resume>
        <p>
        <t>La formation permet d’acquérir les principes et techniques liés à la conception, l’implémentation, l’exploitation de systèmes et applications informatiques sûrs dans un environnement ouvert et hétérogène. Les métiers visés sont ceux du large champ de la </t>
        <i>sécurité informatique</i>
        <t> (applications sécurisées, management de la sécurité, administration d’infrastructures, normes et qualité, audit de sécurité, R&amp;D)</t>
        <i>.</i>
      </p>
        <p>
        <t>La formation apporte des compétences fortes en sécurité et fiabilité des applications (web, mobiles, embarquées), en sécurité organisationnelle, en sécurité des réseaux, en hacking éthique, en protocoles et architectures cryptographiques, en méthodes formelles. L’accent est mis sur le travail en équipe, sur des projets concrets, bénéficiant de l’apport des professionnels intervenant dans la formation.</t>
      </p>
        <p>
        <t>Le parcours est labellisé </t>
        <t>SecNumEdu</t>
      </p>
        <p>
        <i>L’objectif de cette labellisation est d’apporter une assurance qualité aux étudiants et employeurs qu’une formation dans le domaine de la sécurité du numérique répond à une charte et des critères définis par l’</i>
        <i>ANSSI</i>
        <t> </t>
        <i>en collaboration avec les acteurs et professionnels du domaine (établissements d’enseignement supérieur, industriels…).</i>
      </p>
        <p>
        <b>Métiers visés</b>
        <t> :</t>
      </p>
        <ul>
        <li>
